Repository googleapis/nodejs-logging-winston, pull requests merged in 2018-06, with the labels that each got.

#89 fix: prevent permanent merging of labels
  src/index.ts
  test/index.ts
Labels: cla: yes, priority: p1, semver: patch

#95 chore: remove `--bail` from system tests config
  package.json
Labels: cla: yes

#96 fix: fix broken install tests
  package-lock.json
  package.json
  system-test/test-install.ts
  system-test/utils.ts
Labels: cla: yes, in progress

#97 chore: drop node 4 support
  .circleci/config.yml
  package.json
Labels: cla: yes, in progress

#100 chore(package): update to the latest gts and typescript
  package-lock.json
  package.json
  samples/package-lock.json
  system-test/logging-winston.ts
  test/index.ts
Labels: cla: yes, in progress

#104 fix: update linking for samples
  .circleci/config.yml
Labels: cla: yes, in progress

#106 chore: weed the lock file
  samples/package-lock.json
Labels: cla: yes, in progress

#107 fix: drop repo-tools as an exec wrapper
  .circleci/config.yml
  package.json
  samples/package.json
Labels: cla: yes, in progress

#114 chore: udpate packages
  package-lock.json
  package.json
  samples/package-lock.json
  samples/package.json
  tsconfig.json
Labels: cla: yes, in progress
