Repository googleapis/nodejs-logging-winston, pull requests merged in 2019-06, with the labels that each got.

#331 chore: update @google-cloud/common to 2.x
  package-lock.json
  package.json
  system-test/errors-transport.ts
Labels: cla: yes

#336 fix(deps): bump minimum required dependencies
  package-lock.json
  package.json
  samples/package-lock.json
  samples/package.json
Labels: cla: yes

#338 chore: remove root and samples package-lock.json
  package-lock.json
  samples/package-lock.json
Labels: cla: yes

#326 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, status: blocked, type: process

#339 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#340 chore: release 1.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#344 fix(docs): pin to version of compodoc that renders JavaScript/tables
  package.json
Labels: cla: yes

#350 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#351 docs: update docs to reflect sample comments
  README.md
  synth.metadata
Labels: cla: yes

#352 feat: add support for apiEndpoint override
  src/types/core.d.ts
  test/index.ts
Labels: cla: yes

#353 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#356 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#357 chore: release 1.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#358 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
