Repository googleapis/nodejs-logging-winston, pull requests merged in 2019-04, with the labels that each got.

#292 refactor: use execSync for tests
  samples/package.json
  samples/system-test/quickstart.test.js
Labels: cla: yes

#293 refactor: wrap execSync with encoding: utf-8
  samples/system-test/quickstart.test.js
Labels: automerge, cla: yes, unrelated-ci-failure

#294 fix: assign timestamps from log metadata
  src/common.ts
  src/types/core.d.ts
  test/common.ts
Labels: cla: yes

#295 fix: only copy timestamp metadata if it is a date
  src/common.ts
  src/types/core.d.ts
Labels: cla: yes

#296 Release @google-cloud/logging-winston v0.11.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#298 chore: add lock files back
  .gitignore
  package-lock.json
  samples/package-lock.json
  test/winston-2/package-lock.json
Labels: cla: yes

#300 chore: update @google-cloud/common to ^0.32.0
  package.json
  system-test/errors-transport.ts
Labels: cla: yes

#302 docs: use https for links
  README.md
  samples/README.md
Labels: cla: yes

#305 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes
