Repository googleapis/nodejs-logging-winston, pull requests merged in 2019-05, with the labels that each got.

#306 docs: use repo-metadata to generate README
  .cloud-repo-tools.json
  .gitignore
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  package-lock.json
  package.json
  samples/README.md
  samples/setup_explicit.js
  synth.metadata
Labels: cla: yes

#309 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#308 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#311 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#314 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#315 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: automerge, cla: yes

#316 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#313 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, status: blocked

#310 chore(chore): upgrade to gts 1.0.0
  package-lock.json
  package.json
  src/common.ts
  src/index.ts
  src/middleware/express.ts
  src/middleware/make-child-logger.ts
  system-test/errors-transport.ts
  system-test/logging-winston.ts
  system-test/test-install.ts
  system-test/test-middleware-express.ts
  test/common.ts
  test/index.ts
  test/middleware/express.ts
  test/middleware/make-child-logger.ts
Labels: :rotating_light:, cla: yes

#321 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#328 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#327 chore: clean up dev dependencies
  package-lock.json
  package.json
  system-test/errors-transport.ts
Labels: cla: yes

#330 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#332 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
