Repository googleapis/nodejs-logging-winston, pull requests merged in 2020-11, with the labels that each got.

#542 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#543 fix: user provided transport to the logger
  src/middleware/express.ts
  test/middleware/express.ts
Labels: api: logging, cla: yes

#545 chore: add generated files bot to repo
  .github/generated-files-bot.yml
Labels: api: logging, cla: yes, priority: p2, type: process

#546 chore: add blunderbuss
  .github/blunderbuss.yml
Labels: api: logging, automerge, cla: yes, priority: p2

#549 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full
