Repository googleapis/nodejs-logging-winston, pull requests merged in 2020-06, with the labels that each got.

#514 test: skip failing system test
  system-test/logging-winston.ts
Labels: cla: yes

#509 build(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#516 docs: new bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: cla: yes, context: full

#517 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
