Repository googleapis/nodejs-logging-winston, pull requests merged in 2020-07, with the labels that each got.

#518 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#508 test: upstream serialization issues breaking library
  system-test/logging-winston.ts
Labels: cla: yes

#519 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#521 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#522 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: full

#527 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes
