Repository googleapis/nodejs-logging-winston, pull requests merged in 2021-06, with the labels that each got.

#605 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: api: logging, automerge, cla: yes

#599 feat: propagate spanIds
  .readme-partials.yaml
  README.md
  src/common.ts
  src/index.ts
  src/middleware/express.ts
  src/middleware/make-child-logger.ts
  system-test/test-middleware-express.ts
  test/common.ts
  test/middleware/make-child-logger.ts
Labels: api: logging, automerge, cla: yes, kokoro:force-run, kokoro:run, priority: p2, type: feature request

#612 chore: update blunderbuss.yml
  .github/blunderbuss.yml
Labels: api: logging, cla: yes
